# 웹사이트를 빌드하는데 필요한 패키지들

# install.packages("lubridate")
# install.packages("openxlsx")
# install.packages("showtext")
# install.packages("cowplot")
# install.packages("janitor")
# install.packages("tidyverse")
# install.packages("quarto")
# install.packages("rprojroot")
# install.packages("here")
# install.packages("rmarkdown")
# install.packages("knitr")
# install.packages("reticulate")
# install.packages("openxlsx")
# install.packages("showtext")
# install.packages("cowplot")
